---
version: "2"
services:
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TRANSMISSION_TZ}
      - USER=${TRANSMISSION_USER} #optional
      - PASS=${TRANSMISSION_PASS} #optional
    volumes:
      - ${TRANSMISSION_CONFIG_FOLDER}:/config
      - ${TRANSMISSION_DOWNLOAD_FOLDER}:/downloads
      - ${TRANSMISSION_WATCH_FOLDER}:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - ${PLEX_CONFIG_FOLDER}:/config
      - ${PLEX_MOVIES_FOLDER}:/movies
    restart: unless-stopped
