---
  version: "2"
  services:
    plex:
      image: linuxserver/plex
      container_name: plex
      network_mode: host
      environment:
        - PUID=${PLEX_PUID}
        - PGID=${PLEX_PGID}
        - VERSION=docker
        - UMASK_SET=022 #optional
        - PLEX_CLAIM= #optional
      volumes:
        - ${PLEX_CONFIG_FOLDER}:/config
        - ${PLEX_MOVIES_FOLDER}:/movies
      restart: unless-stopped